# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-24 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
